version: '3.9'

x-common-variables: &common-variables
  MYSQL_USER: sampleuser
  MYSQL_PASSWORD: samplepassword
  MYSQL_DATABASE: sampledb
  SERVER_PORT: 8000

services:
  mysql-db:
    image: mysql:5
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: mypass123
    # volumes:
    #   - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin
    links:
      - mysql-db:db
    ports:
      - 8080:80
  server:
    build: ./server
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST: mysql-db
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    command: npm run dev

volumes:
  mysql_data:
